{
 "title": "Overview",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "content": "<div style=\"display: flex; align-items: center\"><img src=\"https://emojify.today/images/emojify_small.png\" alt=\"Consul Icon\"></div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 3 },
   "content": "<div style=\"display: flex; align-items: center\">\n  <img src=\"https://www.datocms-assets.com/2885/1507928925-consul.svg\" alt=\"Consul Icon\">&nbsp;&nbsp;&nbsp;<span style=\"font-size: 22px\">svc/website</span>\n</div>\n<div style=\"font-size: 18px; margin-left: 32px; color: rgba(255, 255, 255, 0.5);\">\n  HTTP requests to the website service via the sidecar proxies.\n</div>"
  },
  {
   "title": "Requests/s",
   "type": "singlestat",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_rq_xx{local_cluster=\"web\", envoy_http_conn_manager_prefix=\"upstream_api_http\", envoy_response_code_class=\"2\"}[30s]))"
    }
   ]
  },
  {
   "title": "Errors/s",
   "type": "singlestat",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_rq_xx{local_cluster=\"api\", envoy_http_conn_manager_prefix=\"upstream_api_http\", envoy_response_code_class=\"5\"}[30s]))"
    }
   ]
  },
  {
   "title": "Website Requests (count)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(envoy_http_downstream_rq_xx{envoy_http_conn_manager_prefix=\"upstream_api_http\"}[30s])) by (envoy_response_code_class)",
     "legendFormat": "{{envoy_response_code_class}}"
    }
   ]
  },
  {
   "title": "Website Requests (time)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "quantile(0.5,irate(envoy_http_downstream_rq_time_bucket{envoy_http_conn_manager_prefix=\"upstream_api_http\"}[30s]))",
     "legendFormat": "0.5"
    },
    {
     "expr": "quantile(0.9,irate(envoy_http_downstream_rq_time_bucket{envoy_http_conn_manager_prefix=\"upstream_api_http\"}[30s]))",
     "legendFormat": "0.9"
    },
    {
     "expr": "quantile(0.95,irate(envoy_http_downstream_rq_time_bucket{envoy_http_conn_manager_prefix=\"upstream_api_http\"}[30s]))",
     "legendFormat": "0.95"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 38 },
   "content": "<div style=\"display: flex; align-items: center\">\n  <img src=\"https://www.datocms-assets.com/2885/1507928925-consul.svg\" alt=\"Consul Icon\">&nbsp;&nbsp;&nbsp;<span style=\"font-size: 22px\">svc/api</span>\n</div>\n<div style=\"font-size: 18px; margin-left: 32px; color: rgba(255, 255, 255, 0.5);\">\n  HTTP requests to the api service via the sidecar proxies.\n</div>"
  },
  {
   "title": "Requests/s - Version 1",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 41 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(envoy_http_downstream_rq_xx{local_cluster=\"api\", envoy_http_conn_manager_prefix=\"public_listener_http\",version=\"1\", envoy_response_code_class=\"2\"}[30s]))"
    }
   ]
  },
  {
   "title": "Errors/s - Version 1",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 41 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(envoy_http_downstream_rq_xx{local_cluster=\"api\", envoy_http_conn_manager_prefix=\"public_listener_http\",version=\"1\", envoy_response_code_class=\"5\"}[30s]))"
    }
   ]
  },
  {
   "title": "Requests/s - Version 2",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 41 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(envoy_http_downstream_rq_xx{local_cluster=\"api\", envoy_http_conn_manager_prefix=\"public_listener_http\",version=\"2\", envoy_response_code_class=\"2\"}[30s]))"
    }
   ]
  },
  {
   "title": "Errors/s - Version 2",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 41 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(envoy_http_downstream_rq_xx{local_cluster=\"api\", envoy_http_conn_manager_prefix=\"public_listener_http\",version=\"2\", envoy_response_code_class=\"5\"}[30s]))"
    }
   ]
  },
  {
   "title": "API Requests (count) - Version 1",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_rq_xx{local_cluster=\"api\", envoy_http_conn_manager_prefix=\"public_listener_http\",version=\"1\"}[30s])) by (version)",
     "legendFormat": "v{{version}}"
    }
   ]
  },
  {
   "title": "API Requests (count)- Version 2",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_rq_xx{local_cluster=\"api\", envoy_http_conn_manager_prefix=\"public_listener_http\",version=\"2\"}[30s])) by (version)",
     "legendFormat": "v{{version}}"
    }
   ]
  },
  {
   "title": "API Requests (time) - Version 1",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "quantile(0.5,irate(envoy_http_downstream_rq_time_bucket{envoy_http_conn_manager_prefix=\"public_listener_http\",local_cluster=\"api\",version=\"1\"}[30s]))",
     "legendFormat": "0.5"
    },
    {
     "expr": "quantile(0.9,irate(envoy_http_downstream_rq_time_bucket{envoy_http_conn_manager_prefix=\"public_listener_http\",local_cluster=\"api\",version=\"1\"}[30s]))",
     "legendFormat": "0.9"
    },
    {
     "expr": "quantile(0.95,irate(envoy_http_downstream_rq_time_bucket{envoy_http_conn_manager_prefix=\"public_listener_http\",local_cluster=\"api\",version=\"1\"}[30s]))",
     "legendFormat": "0.95"
    }
   ]
  },
  {
   "title": "API Requests (time) - Version 1",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "quantile(0.5,irate(envoy_http_downstream_rq_time_bucket{envoy_http_conn_manager_prefix=\"public_listener_http\",local_cluster=\"api\",version=\"2\"}[30s]))",
     "legendFormat": "0.5"
    },
    {
     "expr": "quantile(0.9,irate(envoy_http_downstream_rq_time_bucket{envoy_http_conn_manager_prefix=\"public_listener_http\",local_cluster=\"api\",version=\"2\"}[30s]))",
     "legendFormat": "0.9"
    },
    {
     "expr": "quantile(0.95,irate(envoy_http_downstream_rq_time_bucket{envoy_http_conn_manager_prefix=\"public_listener_http\",local_cluster=\"api\",version=\"2\"}[30s]))",
     "legendFormat": "0.95"
    }
   ]
  }
 ]
}