---
apiVersion: v1
kind: Service
metadata:
  name: whack-a-pod-api
spec:
  selector:
    app: whack-a-pod-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9090
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whack-a-pod-api
  labels:
    app: whack-a-pod-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whack-a-pod-api
  template:
    metadata:
      labels:
        app: whack-a-pod-api
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
        "consul.hashicorp.com/connect-service-protocol": "http"
    spec:
      containers:
      - name: whack-a-pod-api
        image: "nicholasjackson/whack-a-pod-api:websocket"
        imagePullPolicy: Always
        ports:
        - containerPort: 9090
        resources:
          limits:
            cpu: 300m
          requests:
            cpu: 100m
            memory: 100Mi
